ALTER TABLE "Chair" ADD COLUMN IF NOT EXISTS "blockDate"      TEXT;
ALTER TABLE "Chair" ADD COLUMN IF NOT EXISTS "blockTimeStart" TEXT;
ALTER TABLE "Chair" ADD COLUMN IF NOT EXISTS "blockTimeEnd"   TEXT;
